const collectionsActionTypes = {
  SET_COLLECTIONS: "SET_COLLECTIONS",
  ADD_COLLECTIONS: "ADD_COLLECTIONS",
  SET_LAST_COLLECTION_DOC: "SET_LAST_COLLECTION_DOC",
  TOGGLE_IS_HOME_COLLECTIONS_LOADING: "TOGGLE_IS_HOME_COLLECTIONS_LOADING",
};
export default collectionsActionTypes;
