const bagActionTypes = {
  SET_USER_BAG_ITEMS: "SET_USER_BAG_ITEMS",
  ADD_ITEM_TO_USER_BAG: "ADD_ITEM_TO_USER_BAG",
  REMOVE_ITEM_FROM_USER_BAG: "REMOVE_ITEM_FROM_USER_BAG",
  UPDATE_SELECTED_SIZE_AND_QTY_OF_BAG_ITEM:
    "UPDATE_SELECTED_SIZE_AND_QTY_OF_BAG_ITEM",
};

export default bagActionTypes;
