const ordersActionsTypes = {
  SET_ORDERS: "SET_ORDERS",
  ADD_ORDERS: "ADD_ORDERS",
  SET_CURRENT_PAGE: "SET_CURRENT_PAGE",
  SET_LAST_ORDER_DOC: "SET_LAST_ORDER_DOC",
  SET_REFRESH_ORDERS: "SET_REFRESH_ORDERS",
  CANCEL_ORDER: "CANCEL_ORDER",
  FULFILL_ORDER: "FULFILL_ORDER",
  REPLACE_ORDER: "REPLACE_ORDER",
  UPDATE_ORDER_INFO: "UPDATE_ORDER_INFO",
  TOGGLE_IS_ORDERS_LOADING: "TOGGLE_IS_ORDERS_LOADING",
  SET_ORDER_FOR_OPERATION: "SET_ORDER_FOR_OPERATION",
  TOGGLE_SHOW_ORDER_DIALOG: "TOGGLE_SHOW_ORDER_DIALOG",
};

export default ordersActionsTypes;
