const wishlistActionTypes = {
  SET_USER_WISHLIST_ITEMS: "SET_USER_WISHLIST_ITEMS",
  ADD_USER_WISHLIST_ITEM: "ADD_USER_WISHLIST_ITEM",
  REMOVE_USER_WISHLIST_ITEM: "REMOVE_USER_WISHLIST_ITEM",
  TOGGLE_IS_WISHLIST_ITEMS_LOADING: "TOGGLE_IS_WISHLIST_ITEMS_LOADING",
};

export default wishlistActionTypes;
