const filterActionTypes = {
  SET_FILTER_ITEMS: "SET_FILTER_ITEMS",
  SET_ALL_BRANDS_FOR_FILTER: "SET_ALL_BRANDS_FOR_FILTER",
  SET_ALL_COLLECTIONS_FOR_FILTER: "SET_ALL_COLLECTIONS_FOR_FILTER",
  SET_SELECTED_GROUP_FOR_FILTER: "SET_SELECTED_GROUP_FOR_FILTER",
  SELECT_BRAND_FOR_FILTER: "SELECT_BRAND_FOR_FILTER",
  SELECT_COLLECTION_FOR_FILTER: "SELECT_COLLECTION_FOR_FILTER",
  SELECT_GROUP_FOR_FILTER: "SELECT_GROUP_FOR_FILTER",

  TOGGLE_IS_FILTER_ITEMS_LOADING: "TOGGLE_IS_FILTER_ITEMS_LOADING",
  SET_LAST_FILTER_ITEM_DOC: "SET_LAST_FILTER_ITEM_DOC",
  SET_FIRST_FILTER_ITEM_DOC: "SET_FIRST_FILTER_ITEM_DOC",

  SET_FILTER_ITEMS_DOCS: "SET_FILTER_ITEMS_DOCS",
  SET_CURRENT_FILTER_PAGE: "SET_CURRENT_FILTER_PAGE",

  SET_SELECTED_BRANDS_FOR_FILTER: "SET_SELECTED_BRANDS_FOR_FILTER",
  SET_SELECTED_COLLECTIONS_FOR_FILTER: "SET_SELECTED_COLLECTIONS_FOR_FILTER",

  SET_CURRENT_FILTER: "SET_CURRENT_FILTER",
  SET_CURRENT_FILTER_ITEMS: "SET_CURRENT_FILTER_ITEMS",
  ADD_FILTER_ITEMS: "ADD_FILTER_ITEMS",
  ADD_FILTER_ITEMS_DOCS: "ADD_FILTER_ITEMS_DOCS",
  TOGGLE_FILTER_PANEL: "TOGGLE_FILTER_PANEL",
};

export default filterActionTypes;
