const itemPreviewActionsTypes = {
  SET_ITEM_FOR_PREVIEW: "SET_ITEM_FOR_PREVIEW",
  TOGGLE_IS_ITEM_LOADING_FOR_PREVIEW: "TOGGLE_IS_ITEM_LOADING_FOR_PREVIEW",
  TOGGLE_ITEM_IMAGE_PREVIEW_DIALOG: "TOGGLE_ITEM_IMAGE_PREVIEW_DIALOG",
  SET_CURRENT_IMAGE_FOR_IMAGE_PREVIEW_DIALOG:
    "SET_CURRENT_IMAGE_FOR_IMAGE_PREVIEW_DIALOG",
};

export default itemPreviewActionsTypes;
