const brandsActionsTypes = {
  SET_ADMIN_BRANDS: "SET_ADMIN_BRANDS",
  SET_BRANDS_CURRENT_PAGE: "SET_BRANDS_CURRENT_PAGE",
  ADD_ADMIN_BRANDS: "ADD_ADMIN_BRANDS",

  TOGGLE_IS_BRANDS_LOADING: "TOGGLE_IS_BRANDS_LOADING",
  SET_LAST_ADMIN_BRAND_DOC: "SET_LAST_ADMIN_BRAND_DOC",
  TOGGLE_IS_BRANDS_OPERATION_RUNNING: "TOGGLE_IS_BRANDS_OPERATION_RUNNING",
  TOGGLE_ADD_BRAND_DIALOG: "TOGGLE_ADD_BRAND_DIALOG",
  ADD_BRAND: "ADD_BRAND",
  SET_BRAND_FOR_OPERATION: "SET_BRAND_FOR_OPERATION",
  TOGGLE_UPDATE_BRAND_DIALOG: "TOGGLE_UPDATE_BRAND_DIALOG",
  UPDATE_BRAND: "UPDATE_BRAND",
  TOGGLE_DELETE_BRAND_DIALOG: "TOGGLE_DELETE_BRAND_DIALOG",
  DELETE_BRAND: "DELETE_BRAND",
};

export default brandsActionsTypes;
