const checkoutActionsTypes = {
  CHECK_CHECKOUT_STEP: "CHECK_CHECKOUT_STEP",
  SET_CURRENT_CHECKOUT_STEP: "SET_CURRENT_CHECKOUT_STEP",
  SET_CHECKOUT_CART_ITEMS: "SET_CHECKOUT_CART_ITEMS",
  REMOVE_CHECKOUT_CART_ITEM: "REMOVE_CHECKOUT_CART_ITEM",
  SET_SHIPPING_ADDRESS: "SET_SHIPPING_ADDRESS",
  SET_CONTACT_DETAILS: "SET_CONTACT_DETAILS",
  SET_PAYMENT_DETAILS: "SET_PAYMENT_DETAILS",
  SET_CURRENT_PAYMENT_OPTION: "SET_CURRENT_PAYMENT_OPTION",
  TOGGLE_IS_PAYMENT_LOADING: "TOGGLE_IS_PAYMENT_LOADING",
  IS_ORDER_PLACED_SUCCESSFULLY: "IS_ORDER_PLACED_SUCCESSFULLY",
  IS_PAYMENT_SUCCESSFULL: "IS_PAYMENT_SUCCESSFULL",

  SET_CHECKOUT_PAYMENT_DETAILS: "SET_CHECKOUT_PAYMENT_DETAILS",
  SET_CHECKOUT_TO_DEFAULT: "SET_CHECKOUT_TO_DEFAULT",
  TOGGLE_IS_ORDER_PLACING: "TOGGLE_IS_ORDER_PLACING",
};

export default checkoutActionsTypes;
