const contactUsActionsTypes = {
  SET_CONTACT_US_ITEMS: "SET_CONTACT_US_ITEMS",
  TOGGLE_IS_CONTACT_US_ITEMS_LOADING: "TOGGLE_IS_CONTACT_US_ITEMS_LOADING",
  ADD_CONTACT_US_ITEMS: "ADD_CONTACT_US_ITEMS",
  SET_CURRENT_CONTACT_US_PAGE: "SET_CURRENT_CONTACT_US_PAGE",
  SET_LAST_CONTACT_US_DOC: "SET_LAST_CONTACT_US_DOC",
  SET_CONTACT_US_FOR_OPERATION: "SET_CONTACT_US_FOR_OPERATION",
  TOGGLE_REPLAY_CONTACT_US_DIALOG: "TOGGLE_REPLAY_CONTACT_US_DIALOG",
  UPDATE_CONTACT_US_DETAILS: "UPDATE_CONTACT_US_DETAILS",
};

export default contactUsActionsTypes;
