const collectionsActionTypes = {
  SET_ADMIN_COLLECTIONS: "SET_ADMIN_COLLECTIONS",
  TOGGLE_IS_COLLECTIONS_LOADING: "TOGGLE_IS_COLLECTIONS_LOADING",
  SET_LAST_ADMIN_COLLECTION_DOC: "SET_LAST_ADMIN_COLLECTION_DOC",
  SET_COLLECTIONS_CURRENT_PAGE: "SET_COLLECTIONS_CURRENT_PAGE",
  ADD_ADMIN_COLLECTIONS: "ADD_ADMIN_COLLECTIONS",

  TOGGLE_IS_COLLECTIONS_OPERATION_RUNNING:
    "TOGGLE_IS_COLLECTIONS_OPERATION_RUNNING",

  TOGGLE_ADD_COLLECTION_DIALOG: "TOGGLE_ADD_COLLECTION_DIALOG",
  ADD_COLLECTION: "ADD_COLLECTION",

  SET_COLLECTION_FOR_OPERATION: "SET_COLLECTION_FOR_OPERATION",
  TOGGLE_UPDATE_COLLECTION_DIALOG: "TOGGLE_UPDATE_COLLECTION_DIALOG",
  UPDATE_COLLECTION: "UPDATE_COLLECTION",

  TOGGLE_DELETE_COLLECTION_DIALOG: "TOGGLE_DELETE_COLLECTION_DIALOG",
  DELETE_COLLECTION: "DELETE_COLLECTION",
};

export default collectionsActionTypes;
