const ordersActionsTypes = {
  SET_ORDERS: "SET_ORDERS",
  SET_ORDER_TO_CANCEL: "SET_ORDER_TO_CANCEL",
  TOGGLE_CANCEL_ORDER_DIALOG: "TOGGLE_CANCEL_ORDER_DIALOG",
  CANCEL_ORDER: "CANCEL_ORDER",
  ADD_ORDER: "ADD_ORDER",
  UPDATE_ORDER_INFO: "UPDATE_ORDER_INFO",
  ADD_ORDERS: "ADD_ORDERS",
  SET_UNSUBSCRIBE_USER_ORDERS_METHOD: "SET_UNSUBSCRIBE_USER_ORDERS_METHOD",
};
export default ordersActionsTypes;
