const userActionTypes = {
  SET_USERS: "SET_USERS",
  TOGGLE_IS_USERS_LOADING: "TOGGLE_IS_USERS_LOADING",
  SET_FIRST_USER_DOC: "SET_FIRST_USER_DOC",
  SET_LAST_USER_DOC: "SET_LAST_USER_DOC",
  UPDATE_USER_ROLE: "UPDATE_USER_ROLE",
  TOGGLE_IS_OPERATION_RUNNING: "TOGGLE_IS_OPERATION_RUNNING",

  TOGGLE_ADD_USER_DIALOG: "TOGGLE_ADD_USER_DIALOG",
  ADD_NEW_USER: "ADD_NEW_USER",
  DISABLE_USER: "DISABLE_USER",
  ENABLE_USER: "ENABLE_USER",
  TOGGLE_DELETE_USER_DIALOG: "TOGGLE_DELETE_USER_DIALOG",
  SET_USER_TO_DELETE: "SET_USER_TO_DELETE",
  DELETE_USER: "DELETE_USER",
  SET_USER_FOR_OPERATION: "SET_USER_FOR_OPERATION",
  TOGGLE_EDIT_USER_DIALOG: "TOGGLE_EDIT_USER_DIALOG",
  EDIT_USER: "EDIT_USER",
};

export default userActionTypes;
