const userActionTypes = {
  SET_CURRENT_USER: "SET_CURRENT_USER",
  UPDATE_CURRENT_USER_NAME: "UPDATE_CURRENT_USER_NAME",
  IS_OPERATION_RUNNING: "IS_OPERATION_RUNNING",
  UDPATE_EMAIL_DIALOG: "UDPATE_EMAIL_DIALOG",
  SET_IS_EMAIL_VERIFICATION_LINK_SENT: "SET_IS_EMAIL_VERIFICATION_LINK_SENT",
  IS_PASSWORD_CHANGE_LINK_SENT: "IS_PASSWORD_CHANGE_LINK_SENT",
  DELETE_USER_DIALOG: "DELETE_USER_DIALOG",
  DELETE_CURRENT_USER: "DELETE_CURRENT_USER",

  CONVERT_WISHLIST_ARR_TO_ITEMS: "CONVERT_WISHLIST_ARR_TO_ITEMS",
  ADD_ITEM_TO_WISHLIST: "ADD_ITEM_TO_WISHLIST",
  REMOVE_ITEM_FROM_WISHLIST: "REMOVE_ITEM_FROM_WISHLIST",
  ADD_ITEM_TO_BAG: "ADD_ITEM_TO_BAG",
  REMOVE_ITEM_FROM_BAG: "REMOVE_ITEM_FROM_BAG",
  ADD_ORDER_TO_USER: "ADD_ORDER_TO_USER",

  SET_CURRENT_USER_ADDRESS: "SET_CURRENT_USER_ADDRESS",
  SET_CURRENT_USER_PHONE_NO: "SET_CURRENT_USER_PHONE_NO",
};
export default userActionTypes;
